In [1]:
import numpy as np
a=[1,2,3,4,5]
type(a)

list

In [4]:
x=np.array(a)
print(x)

[1 2 3 4 5]


In [5]:
x=np.array(a)
print(x)

[1 2 3 4 5]


In [6]:
type(x)

numpy.ndarray

In [7]:
A=[1,2,3,4,5


In [14]:
import numpy as np
A=[1,2,3,4,5]
b=[10,20,30,0,0]
f = np.array([A,b])
print(f)

[[ 1  2  3  4  5]
 [10 20 30  0  0]]


In [15]:
x=np.array([1,2,3,4],dtype=np.float32)
print(x)

[1. 2. 3. 4.]


In [17]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [21]:
x=np.random.rand(2,5)
print(x)

[[0.51993748 0.3627264  0.61736524 0.67109273 0.99092992]
 [0.45971078 0.45132212 0.5628362  0.65474766 0.70867767]]


array([[15, 17, 13],
       [ 9,  8, 15],
       [11, 10, 12]], dtype=int32)

Signature: np.random.rand(*args)
Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      method

In [23]:
np.random.randint??
np.random.randn(2,5)

array([[-1.2458826 ,  0.61522476,  0.42494593,  0.22598545,  1.35749815],
       [ 1.6075061 ,  0.71281539,  0.33202774, -0.78699498, -0.89275725]])

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [24]:
np.random.rand??
np.random.randint(1,20,size=(3,3))

array([[ 1,  2, 10],
       [11, 14,  4],
       [ 1,  8, 16]], dtype=int32)

Signature: np.random.rand(*args)
Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      method

In [27]:

np.random.choice([2,3,4,7,8,10])

np.int64(10)

In [28]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [29]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [30]:
x=np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [31]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [32]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)

[10 20 30 40 50]


In [35]:
x.ndim

1

In [37]:
b=[1,2,3,4,5]
y=np.array([a,b])

In [38]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [39]:
y.ndim

2

In [40]:
y.shape

(2, 5)

In [41]:
y.size

10

In [42]:
x=np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [43]:
a=np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [44]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [45]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [46]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
x.size

15

In [48]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [49]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [50]:
y=x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [51]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [53]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [54]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [55]:
a[2:6]

array([3, 4, 5, 6])